import { Navigation } from "@/components/navigation"
import { RouteHero } from "@/components/route-hero"
import { RouteTimeline } from "@/components/route-timeline"
import { RoutePackage } from "@/components/route-package"
import { notFound } from "next/navigation"

const routeData = {
  costera: {
    id: "costera",
    name: "Ruta Costera Atlántica",
    description: "Recorrido por las costas atlánticas desde Mar del Plata hasta Puerto Deseado en Santa Cruz",
    duration: "12-15 días",
    difficulty: "Moderada",
    heroImage: "https://ik.imagekit.io/ankxi835d/rutasimg/ballena-paisaje-hotel-peninsula-valdes-puerto-madryn-chubut-argentina.jpeg?updatedAt=1763067101439",
    cities: [
      {
        name: "Mar del Plata",
        distance: 0,
        time: "0 hrs",
        description: "Punto de partida con gran infraestructura turística. Surf, gastronomía y vida nocturna.",
        accommodation: {
          id: "domo-atlantico",
          name: "Domo Atlántico",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/mardel.jpg?updatedAt=1763239749655",
          price: "$120",
          rating: 4.7,
        },
      },
      {
        name: "Las Grutas",
        distance: 880,
        time: "10 hrs",
        description: "Aguas cálidas, acantilados y turismo familiar en Río Negro.",
        accommodation: {
          id: "domo-grutas",
          name: "Domo Las Grutas",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/Las-Grutas-Playa.webp?updatedAt=1763066851942",
          price: "$140",
          rating: 4.8,
        },
      },
      {
        name: "Playas Doradas",
        distance: 130,
        time: "2 hrs",
        description: "Playas vírgenes y tranquilidad. Ideal para domos ecológicos y desconexión.",
        accommodation: {
          id: "domo-playas-doradas",
          name: "Domo Playas Doradas",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/playas-doradas-rio-negro.jpg?updatedAt=1763065075128",
          price: "$130",
          rating: 4.6,
        },
      },
      {
        name: "Puerto Pirámides",
        distance: 180,
        time: "3 hrs",
        description: "Avistaje de ballenas, buceo y Península Valdés.",
        accommodation: {
          id: "domo-piramides",
          name: "Domo Puerto Pirámides",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/puertomadryn.jpg?updatedAt=1763065074652",
          price: "$180",
          rating: 4.9,
        },
      },
      {
        name: "Camarones",
        distance: 270,
        time: "3.5 hrs",
        description: "Pueblo costero, pesca y naturaleza pura. Experiencias de aventura.",
        accommodation: {
          id: "domo-camarones",
          name: "Domo Camarones",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/pinguinos.jpg?updatedAt=1763065075126",
          price: "$135",
          rating: 4.5,
        },
      },
      {
        name: "Puerto Deseado",
        distance: 300,
        time: "3.5 hrs",
        description: "Reserva natural, fauna marina e historia de exploradores.",
        accommodation: {
          id: "domo-deseado",
          name: "Domo Puerto Deseado",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/PtoDeseado27-secTurismo-1024x691-1.jpeg?updatedAt=1763239749480",
          price: "$145",
          rating: 4.7,
        },
      },
    ],
    packagePrice: "$2,150",
    packageIncludes: [
      "12 noches en domos costeros",
      "Desayuno incluido",
      "Seguro de viaje completo",
    ],
  },
  andina: {
    id: "andina",
    name: "Ruta Andina Norte",
    description: "Atravesá el noroeste argentino desde Purmamarca hasta Antofagasta de la Sierra",
    duration: "10-12 días",
    difficulty: "Moderada-Difícil",
    heroImage: "https://ik.imagekit.io/ankxi835d/rutasimg/cafayateruta.webp?updatedAt=1763393476008",
    cities: [
      {
        name: "Purmamarca",
        distance: 0,
        time: "0 hrs",
        description: "Cerro de los Siete Colores, artesanías y trekking en Jujuy.",
        accommodation: {
          id: "domo-purmamarca",
          name: "Domo Purmamarca",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/cerroSieteColores.jpg?updatedAt=1763065075237",
          price: "$150",
          rating: 4.8,
        },
      },
      {
        name: "Cachi",
        distance: 200,
        time: "5 hrs",
        description: "Arquitectura colonial, cerros nevados y museo arqueológico en Salta.",
        accommodation: {
          id: "domo-cachi",
          name: "Domo Cachi",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/cachi.jpg?updatedAt=1763393475709",
          price: "$145",
          rating: 4.7,
        },
      },
      {
        name: "Cafayate",
        distance: 160,
        time: "3 hrs",
        description: "Bodegas de altura y Quebrada de las Conchas.",
        accommodation: {
          id: "domo-cafayate",
          name: "Domo Cafayate",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/cafayate.jpg?updatedAt=1763393475742",
          price: "$170",
          rating: 4.9,
        },
      },
      {
        name: "Fiambalá",
        distance: 280,
        time: "5 hrs",
        description: "Termas naturales, dunas y Ruta del Adobe en Catamarca.",
        accommodation: {
          id: "domo-fiambala",
          name: "Domo Fiambalá",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/fiambala.jpg?updatedAt=1763393475932",
          price: "$155",
          rating: 4.6,
        },
      },
      {
        name: "Antofagasta de la Sierra",
        distance: 200,
        time: "4 hrs",
        description: "Campo de Piedra Pómez, Volcán Galán. Requiere 4x4.",
        accommodation: {
          id: "domo-antofagasta",
          name: "Domo Antofagasta",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/antofagasta-de-la-sierra-6.jpg?updatedAt=1763393475697",
          price: "$165",
          rating: 4.8,
        },
      },
    ],
    packagePrice: "$2,350",
    packageIncludes: [
      "10 noches en domos de altura",
      "Desayuno y cena incluidos",
      "Guía de montaña certificado",
      "Transporte 4x4 entre ciudades",
      "Visita a termas de Fiambalá",
      "Equipo de trekking",
      "Seguro de viaje",
    ],
  },
  litoral: {
    id: "litoral",
    name: "Ruta Litoral",
    description: "Descubrí el litoral argentino desde Iguazú hasta Formosa, pasando por los Esteros del Iberá",
    duration: "8-10 días",
    difficulty: "Fácil",
    heroImage: "/iguazu-falls-rainforest-argentina.jpg",
    cities: [
      {
        name: "Puerto Iguazú",
        distance: 0,
        time: "0 hrs",
        description: "Cataratas del Iguazú, selva misionera y triple frontera.",
        accommodation: {
          id: "domo-iguazu",
          name: "Domo Selva Iguazú",
          image: "/domo-selva-exterior.jpg",
          price: "$180",
          rating: 4.9,
        },
      },
      {
        name: "San Ignacio",
        distance: 245,
        time: "3 hrs",
        description: "Ruinas jesuíticas, río Paraná y cultura guaraní.",
        accommodation: {
          id: "domo-san-ignacio",
          name: "Domo San Ignacio",
          image: "/domo-cultural-exterior.jpg",
          price: "$140",
          rating: 4.6,
        },
      },
      {
        name: "Colonia Pellegrini",
        distance: 350,
        time: "5 hrs",
        description: "Esteros del Iberá, fauna autóctona y rewilding.",
        accommodation: {
          id: "domo-ibera",
          name: "Domo Iberá",
          image: "/domo-esteros-exterior.jpg",
          price: "$165",
          rating: 4.8,
        },
      },
      {
        name: "Clorinda",
        distance: 450,
        time: "6 hrs",
        description: "Río Pilcomayo, frontera con Paraguay y cultura ribereña.",
        accommodation: {
          id: "domo-clorinda",
          name: "Domo Clorinda",
          image: "/domo-ribereno-exterior.jpg",
          price: "$130",
          rating: 4.5,
        },
      },
      {
        name: "Formosa Capital",
        distance: 110,
        time: "1 hr",
        description: "Costanera sobre el río Paraguay, lagunas y artesanías.",
        accommodation: {
          id: "domo-formosa",
          name: "Domo Formosa",
          image: "/domo-urbano-exterior.jpg",
          price: "$135",
          rating: 4.6,
        },
      },
    ],
    packagePrice: "$1,850",
    packageIncludes: [
      "8 noches en domos selváticos",
      "Desayuno incluido",
      "Guía especializado en fauna",
      "Transporte entre ciudades",
      "Entrada a Cataratas del Iguazú",
      "Safari fotográfico en Iberá",
      "Seguro de viaje",
    ],
  },
  patagonica: {
    id: "patagonica",
    name: "Ruta Patagónica Completa",
    description: "La gran travesía patagónica desde El Calafate hasta el Volcán Lanín",
    duration: "16-20 días",
    difficulty: "Moderada-Difícil",
    heroImage: "https://ik.imagekit.io/ankxi835d/rutasimg/costanera-bariloche-3.jpg?updatedAt=1763579562689",
    cities: [
      {
        name: "El Calafate",
        distance: 0,
        time: "0 hrs",
        description: "Glaciar Perito Moreno, Lago Argentino y navegación.",
        accommodation: {
          id: "domo-glaciar",
          name: "Domo Glaciar",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/calafate2.jpg?updatedAt=1763579749151",
          price: "$220",
          rating: 5.0,
        },
      },
      {
        name: "El Chaltén",
        distance: 213,
        time: "3 hrs",
        description: "Cerro Fitz Roy, Laguna de los Tres y trekking de montaña.",
        accommodation: {
          id: "domo-chalten",
          name: "Domo Chaltén",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/elchanten.webp?updatedAt=1763579562890",
          price: "$210",
          rating: 4.9,
        },
      },
      {
        name: "Los Antiguos",
        distance: 500,
        time: "10 hrs",
        description: "Lago Buenos Aires, cerezas y frontera con Chile.",
        accommodation: {
          id: "domo-antiguos",
          name: "Domo Los Antiguos",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/entrada-los-antiguos.webp?updatedAt=1763579562695",
          price: "$170",
          rating: 4.7,
        },
      },
      {
        name: "Esquel",
        distance: 300,
        time: "6 hrs",
        description: "Parque Nacional Los Alerces y La Trochita (tren histórico).",
        accommodation: {
          id: "domo-esquel",
          name: "Domo Esquel",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/esquel.jpg?updatedAt=1763579562652",
          price: "$165",
          rating: 4.6,
        },
      },
      {
        name: "Bariloche",
        distance: 190,
        time: "3 hrs",
        description: "Lago Nahuel Huapi, Cerro Catedral y Circuito Chico.",
        accommodation: {
          id: "domo-bariloche",
          name: "Domo Bariloche",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/Cerro-catedral-san-carlos-de-Bariloche.jpeg?updatedAt=1763579562860",
          price: "$190",
          rating: 4.9,
        },
      },
      {
        name: "Villa Traful",
        distance: 65,
        time: "2 hrs",
        description: "Lago Traful, bosque sumergido y tranquilidad absoluta.",
        accommodation: {
          id: "domo-traful",
          name: "Domo Villa Traful",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/Playa-del-lago-Traful-1024x576.jpg?updatedAt=1763579562703",
          price: "$175",
          rating: 4.8,
        },
      },
      {
        name: "San Martín de los Andes",
        distance: 105,
        time: "2 hrs",
        description: "Lago Lácar, miradores y gastronomía patagónica.",
        accommodation: {
          id: "domo-san-martin",
          name: "Domo San Martín",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/sanmartin2.jpg?updatedAt=1763579562659",
          price: "$185",
          rating: 4.9,
        },
      },
      {
        name: "Volcán Lanín",
        distance: 45,
        time: "45 min",
        description: "Volcán Lanín, Lago Huechulafquen y Parque Nacional Lanín.",
        accommodation: {
          id: "domo-lanin",
          name: "Domo Lanín",
          image: "https://ik.imagekit.io/ankxi835d/rutasimg/sanmartin.jpg?updatedAt=1763579562845",
          price: "$195",
          rating: 4.8,
        },
      },
    ],
    packagePrice: "$3,850",
    packageIncludes: [
      "16 noches en domos premium patagónicos",
      "Todas las comidas incluidas",
      "Guía patagónico experto",
      "Transporte terrestre entre todas las ciudades",
      "Excursión al Glaciar Perito Moreno",
      "Trekking al Fitz Roy con guía",
      "Navegación en lagos patagónicos",
      "Seguro de viaje integral",
    ],
  },
  vinedos: {
    id: "vinedos",
    name: "Ruta de los Viñedos Cordilleranos",
    description: "Ruta enoturística desde Mendoza hasta La Rioja pasando por los mejores viñedos de altura",
    duration: "8-10 días",
    difficulty: "Fácil",
    heroImage: "/mendoza-vineyards-andes-mountains-argentina.jpg",
    cities: [
      {
        name: "Mendoza Capital",
        distance: 0,
        time: "0 hrs",
        description: "Bodegas de Maipú y Luján de Cuyo, gastronomía cuyana.",
        accommodation: {
          id: "domo-mendoza",
          name: "Domo Viñedo Mendoza",
          image: "/domo-vinedo-exterior-mendoza.jpg",
          price: "$200",
          rating: 5.0,
        },
      },
      {
        name: "Potrerillos",
        distance: 70,
        time: "1 hr",
        description: "Embalse, deportes acuáticos y vistas a la cordillera.",
        accommodation: {
          id: "domo-potrerillos",
          name: "Domo Potrerillos",
          image: "/domo-potrerillos-lago.jpg",
          price: "$170",
          rating: 4.7,
        },
      },
      {
        name: "Calingasta (Barreal)",
        distance: 230,
        time: "4 hrs",
        description: "Valle de Calingasta, Parque El Leoncito y astroturismo.",
        accommodation: {
          id: "domo-barreal",
          name: "Domo Barreal",
          image: "/domo-desertico-barreal.jpg",
          price: "$165",
          rating: 4.8,
        },
      },
      {
        name: "San Juan Capital",
        distance: 180,
        time: "3 hrs",
        description: "Vinos Syrah, Ruta del Olivo y cultura cuyana.",
        accommodation: {
          id: "domo-san-juan",
          name: "Domo San Juan",
          image: "/domo-urbano-san-juan.jpg",
          price: "$155",
          rating: 4.6,
        },
      },
      {
        name: "Huaco (Jáchal)",
        distance: 160,
        time: "2.5 hrs",
        description: "Quebrada de Huaco, historia colonial y paisajes rocosos.",
        accommodation: {
          id: "domo-huaco",
          name: "Domo Huaco",
          image: "/domo-rustico-huaco.jpg",
          price: "$145",
          rating: 4.5,
        },
      },
      {
        name: "Villa Unión",
        distance: 120,
        time: "2 hrs",
        description: "Parque Nacional Talampaya y Valle del Bermejo.",
        accommodation: {
          id: "domo-villa-union",
          name: "Domo Villa Unión",
          image: "/domo-desertico-talampaya.jpg",
          price: "$160",
          rating: 4.7,
        },
      },
      {
        name: "La Rioja Capital",
        distance: 270,
        time: "4 hrs",
        description: "Ruta del Torrontés, cultura riojana y termas cercanas.",
        accommodation: {
          id: "domo-la-rioja",
          name: "Domo La Rioja",
          image: "/domo-urbano-la-rioja.jpg",
          price: "$150",
          rating: 4.6,
        },
      },
    ],
    packagePrice: "$2,450",
    packageIncludes: [
      "9 noches en domos entre viñedos",
      "Desayuno gourmet incluido",
      "Catas de vino en 8 bodegas premium",
      "Transporte privado entre ciudades",
      "Cenas maridaje (4 incluidas)",
      "Tour enológico con sommelier",
      "Visita a Parque Talampaya",
      "Seguro de viaje",
    ],
  },
    litoral_norte: {
  id: "litoral",
  name: "Ruta Litoral del Norte",
  description: "Recorrido por el noreste argentino desde Puerto Iguazú hasta Formosa Capital, atravesando selvas, esteros y culturas ribereñas.",
  duration: "10-12 días",
  difficulty: "Moderada",
  heroImage: "https://ik.imagekit.io/ankxi835d/rutasimg/esterosibera.jpg?updatedAt=1763093784020",
  cities: [
    {
      name: "Puerto Iguazú",
      distance: 0,
      time: "0 hrs",
      description: "Inicio en la selva misionera. Cataratas del Iguazú, triple frontera y biodiversidad exuberante.",
      accommodation: {
        id: "domo-iguazu",
        name: "Domo Selvático Premium",
        image: "/domo-selva-iguazu-exterior.jpg",
        price: "$160",
        rating: 4.9,
      },
    },
    {
      name: "San Ignacio",
      distance: 230,
      time: "3 hrs",
      description: "Ruinas jesuíticas, río Paraná y cultura guaraní viva.",
      accommodation: {
        id: "domo-san-ignacio",
        name: "Domo Cultural Rústico",
        image: "/domo-cultural-guarani.jpg",
        price: "$130",
        rating: 4.6,
      },
    },
    {
      name: "Colonia Pellegrini / Iberá",
      distance: 400,
      time: "5 hrs",
      description: "Esteros del Iberá, fauna autóctona y navegación entre lagunas.",
      accommodation: {
        id: "domo-ibera",
        name: "Domo Elevado Ecológico",
        image: "/domo-ibera-naturaleza.jpg",
        price: "$150",
        rating: 4.8,
      },
    },
    {
      name: "Clorinda",
      distance: 480,
      time: "6 hrs",
      description: "Río Pilcomayo, frontera con Paraguay y cultura ribereña.",
      accommodation: {
        id: "domo-clorinda",
        name: "Domo Ribereño",
        image: "https://ik.imagekit.io/ankxi835d/rutasimg/pn_rio_pilcomayo_ecosistema_ph_parquesnacionales.jpg?updatedAt=1763093783575",
        price: "$125",
        rating: 4.5,
      },
    },
    {
      name: "Formosa Capital",
      distance: 100,
      time: "1 hr",
      description: "Costanera sobre el río Paraguay, lagunas urbanas y artesanías locales.",
      accommodation: {
        id: "domo-formosa",
        name: "Domo Urbano Ecológico",
        image: "/domo-formosa-cultural.jpg",
        price: "$140",
        rating: 4.7,
      },
    },
  ],
  packagePrice: "$1,950",
  packageIncludes: [
    "10 noches en domos temáticos",
    "Desayuno regional incluido",
    "Guía turístico especializado",
    "Transporte entre destinos",
    "Avistaje en Esteros del Iberá",
    "Seguro de viaje completo",
  ],
}
}

export default async function RouteDetailPage({ params }: { params: Promise<{ routeId: string }> }) {
  const { routeId } = await params
  const route = routeData[routeId as keyof typeof routeData]

  if (!route) {
    notFound()
  }

  return (
    <main className="min-h-screen bg-background">
      <Navigation />
      <RouteHero route={route} />
      <RoutePackage route={route} />
      <RouteTimeline route={route} />
    </main>
  )
}
