import type { Accommodation } from './accommodation.entity';

export const seedAccommodations: Accommodation[] = [
  {
    id: 'domo-mar-plata',
    name: 'Domo Atlántico',
    cityId: 'mar-del-plata',
    city: 'Mar del Plata',
    type: 'domo',
    description: 'Domo con vista panorámica al océano Atlántico, perfecto para surfistas.',
    amenities: ['Vista al mar', 'WiFi', 'Desayuno', 'Estacionamiento', 'Tabla de surf'],
    pricePerNight: 85,
    rating: 4.8,
    reviewCount: 124,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/mardel.jpg?updatedAt=1763239749658'],
    maxGuests: 4,
  },
  {
    id: 'domo-grutas',
    name: 'Domo Aguas Cálidas',
    cityId: 'las-grutas',
    city: 'Las Grutas',
    type: 'domo',
    description: 'Domo ecológico cerca de las playas de aguas más cálidas de Argentina.',
    amenities: ['Cerca de la playa', 'WiFi', 'Cocina', 'Parrilla'],
    pricePerNight: 75,
    rating: 4.7,
    reviewCount: 89,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/Las-Grutas-Playa.webp?updatedAt=1763066851942'],
    maxGuests: 3,
  },
  {
    id: 'domo-doradas',
    name: 'Domo Silvestre',
    cityId: 'playas-doradas',
    city: 'Playas Doradas',
    type: 'domo',
    description: 'Desconexión total en playas vírgenes, ideal para contemplación.',
    amenities: ['Aislamiento', 'Fogón', 'Observación de estrellas'],
    pricePerNight: 65,
    rating: 4.9,
    reviewCount: 56,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/playas-doradas-rio-negro.jpg?updatedAt=1763065075128'],
    maxGuests: 2,
  },
  {
    id: 'domo-piramides',
    name: 'Domo Ballenas',
    cityId: 'puerto-piramides',
    city: 'Puerto Pirámides',
    type: 'domo',
    description: 'Vista al mar desde donde podrás avistar ballenas en temporada.',
    amenities: ['Vista al mar', 'Calefacción', 'WiFi', 'Tours incluidos'],
    pricePerNight: 120,
    rating: 4.9,
    reviewCount: 203,
    images: [
      'https://ik.imagekit.io/ankxi835d/rutasimg/ballena-paisaje-hotel-peninsula-valdes-puerto-madryn-chubut-argentina.jpeg?updatedAt=1763067101439',
    ],
    maxGuests: 4,
  },
  {
    id: 'domo-camarones',
    name: 'Domo Pingüinero',
    cityId: 'camarones',
    city: 'Camarones',
    type: 'domo',
    description: 'Experiencia rústica cerca de la pingüinera de Cabo Dos Bahías.',
    amenities: ['Rústico', 'Fogón', 'Excursiones'],
    pricePerNight: 55,
    rating: 4.6,
    reviewCount: 34,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/pinguinos.jpg?updatedAt=1763065075126'],
    maxGuests: 2,
  },
  {
    id: 'domo-deseado',
    name: 'Domo Explorador',
    cityId: 'puerto-deseado',
    city: 'Puerto Deseado',
    type: 'domo',
    description: 'Domo ecológico con enfoque en la historia de exploradores.',
    amenities: ['Ecológico', 'WiFi', 'Tours a la ría', 'Biblioteca'],
    pricePerNight: 70,
    rating: 4.7,
    reviewCount: 67,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/PtoDeseado27-secTurismo-1024x691-1.jpeg?updatedAt=1763239749483'],
    maxGuests: 3,
  },
  {
    id: 'domo-purmamarca',
    name: 'Domo Siete Colores',
    cityId: 'purmamarca',
    city: 'Purmamarca',
    type: 'domo',
    description: 'Domo ecológico con vista panorámica al Cerro de los Siete Colores.',
    amenities: ['Vista al cerro', 'Calefacción', 'Desayuno andino', 'WiFi'],
    pricePerNight: 95,
    rating: 4.9,
    reviewCount: 187,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/cerroSieteColores.jpg?updatedAt=1763065075237'],
    maxGuests: 4,
  },
  {
    id: 'domo-cachi',
    name: 'Domo Calchaquí',
    cityId: 'cachi',
    city: 'Cachi',
    type: 'domo',
    description: 'Estilo rústico-montaña con vistas a los cerros nevados.',
    amenities: ['Vista a montañas', 'Calefacción', 'Fogón'],
    pricePerNight: 80,
    rating: 4.8,
    reviewCount: 92,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/cachi.jpg?updatedAt=1763393475709'],
    maxGuests: 3,
  },
  {
    id: 'domo-cafayate',
    name: 'Domo del Vino',
    cityId: 'cafayate',
    city: 'Cafayate',
    type: 'domo',
    description: 'Integrado a viñedos con catas incluidas y gastronomía regional.',
    amenities: ['En viñedo', 'Cata de vinos', 'Gastronomía', 'Piscina'],
    pricePerNight: 130,
    rating: 4.9,
    reviewCount: 245,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/cafayate.jpg?updatedAt=1763393475742'],
    maxGuests: 4,
  },
  {
    id: 'domo-fiambala',
    name: 'Domo Termal',
    cityId: 'fiambala',
    city: 'Fiambalá',
    type: 'domo',
    description: 'Wellness y relax con acceso exclusivo a termas naturales.',
    amenities: ['Acceso a termas', 'Spa', 'Masajes', 'Yoga'],
    pricePerNight: 110,
    rating: 4.8,
    reviewCount: 156,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/fiambala.jpg?updatedAt=1763393475932'],
    maxGuests: 2,
  },
  {
    id: 'domo-antofagasta',
    name: 'Domo Lunar',
    cityId: 'antofagasta-sierra',
    city: 'Antofagasta de la Sierra',
    type: 'domo',
    description: 'Aventura extrema y astroturismo en paisajes lunares únicos.',
    amenities: ['Aislamiento total', 'Telescopio', 'Tours 4x4', 'Guía'],
    pricePerNight: 150,
    rating: 5.0,
    reviewCount: 78,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/antofagasta-de-la-sierra-6.jpg?updatedAt=1763393475697'],
    maxGuests: 2,
  },
  {
    id: 'domo-iguazu',
    name: 'Domo Selva',
    cityId: 'puerto-iguazu',
    city: 'Puerto Iguazú',
    type: 'domo',
    description: 'Premium selvático con actividades de avistaje y gastronomía regional.',
    amenities: ['En la selva', 'Pileta', 'Tours Cataratas', 'Spa'],
    pricePerNight: 180,
    rating: 4.9,
    reviewCount: 312,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/cataratas1.jpg?updatedAt=1763065074428'],
    maxGuests: 4,
  },
  {
    id: 'domo-san-ignacio',
    name: 'Domo Jesuita',
    cityId: 'san-ignacio',
    city: 'San Ignacio',
    type: 'domo',
    description: 'Rústico cultural con experiencias históricas y talleres artesanales.',
    amenities: ['Tour ruinas', 'Talleres', 'Cultura guaraní'],
    pricePerNight: 70,
    rating: 4.7,
    reviewCount: 89,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/ruinas-san-ignacio-misiones-28122021in5-2.jpg?updatedAt=1765076299659'],
    maxGuests: 3,
  },
  {
    id: 'domo-ibera',
    name: 'Domo Esteros',
    cityId: 'colonia-pellegrini',
    city: 'Colonia Pellegrini',
    type: 'domo',
    description: 'Ecológico elevado con vista a los esteros y actividades de naturaleza.',
    amenities: ['Vista a esteros', 'Safari fotográfico', 'Kayak', 'Guía'],
    pricePerNight: 140,
    rating: 4.9,
    reviewCount: 178,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/esterosibera.jpg?updatedAt=1763093784020'],
    maxGuests: 4,
  },
  {
    id: 'domo-clorinda',
    name: 'Domo Ribereño',
    cityId: 'clorinda',
    city: 'Clorinda',
    type: 'domo',
    description: 'Estilo ribereño con pesca deportiva y navegación.',
    amenities: ['Pesca', 'Navegación', 'Gastronomía local'],
    pricePerNight: 60,
    rating: 4.5,
    reviewCount: 45,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/pn_rio_pilcomayo_ecosistema_ph_parquesnacionales.jpg?updatedAt=1763093783575'],
    maxGuests: 3,
  },
  {
    id: 'domo-formosa',
    name: 'Domo Urbano Eco',
    cityId: 'formosa-capital',
    city: 'Formosa',
    type: 'domo',
    description: 'Urbano ecológico con integración a circuitos culturales.',
    amenities: ['Céntrico', 'Tours culturales', 'WiFi', 'AC'],
    pricePerNight: 65,
    rating: 4.6,
    reviewCount: 52,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/portada-formosa-2.jpg?updatedAt=1765076405613'],
    maxGuests: 2,
  },
  {
    id: 'domo-calafate',
    name: 'Domo Glaciar',
    cityId: 'el-calafate',
    city: 'El Calafate',
    type: 'domo',
    description: 'Estilo glaciar con vista al lago y calefacción eficiente.',
    amenities: ['Vista al lago', 'Calefacción', 'Tours glaciar', 'Desayuno'],
    pricePerNight: 160,
    rating: 4.9,
    reviewCount: 289,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/calafate2.jpg?updatedAt=1763579749158'],
    maxGuests: 4,
  },
  {
    id: 'domo-chalten',
    name: 'Domo Fitz Roy',
    cityId: 'el-chalten',
    city: 'El Chaltén',
    type: 'domo',
    description: 'Aventura alpina con servicios para senderistas exigentes.',
    amenities: ['Vista Fitz Roy', 'Equipo trekking', 'Desayuno energético'],
    pricePerNight: 140,
    rating: 4.9,
    reviewCount: 234,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/elchanten.webp?updatedAt=1763579562890'],
    maxGuests: 3,
  },
  {
    id: 'domo-antiguos',
    name: 'Domo Lago Buenos Aires',
    cityId: 'los-antiguos',
    city: 'Los Antiguos',
    type: 'domo',
    description: 'Lacustre con vista al lago más grande de Argentina.',
    amenities: ['Vista al lago', 'Pesca', 'Kayak', 'Cerezas'],
    pricePerNight: 85,
    rating: 4.7,
    reviewCount: 67,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/entrada-los-antiguos.webp?updatedAt=1763579562695'],
    maxGuests: 3,
  },
  {
    id: 'domo-esquel',
    name: 'Domo Alerces',
    cityId: 'esquel',
    city: 'Esquel',
    type: 'domo',
    description: 'Ecológico en bosque andino cerca del Parque Los Alerces.',
    amenities: ['En bosque', 'Senderismo', 'La Trochita'],
    pricePerNight: 90,
    rating: 4.8,
    reviewCount: 112,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/esquel.jpg?updatedAt=1763579562652'],
    maxGuests: 4,
  },
  {
    id: 'domo-bariloche',
    name: 'Domo Nahuel Huapi',
    cityId: 'bariloche',
    city: 'San Carlos de Bariloche',
    type: 'domo',
    description: 'Estilo alpino integrado al bosque con vista al lago.',
    amenities: ['Vista lago', 'Chocolate', 'Cerveza artesanal', 'Ski'],
    pricePerNight: 170,
    rating: 4.9,
    reviewCount: 356,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/Cerro-catedral-san-carlos-de-Bariloche.jpeg?updatedAt=1763579562860'],
    maxGuests: 4,
  },
  {
    id: 'domo-traful',
    name: 'Domo Silencio',
    cityId: 'villa-traful',
    city: 'Villa Traful',
    type: 'domo',
    description: 'Contemplación y desconexión total junto al lago cristalino.',
    amenities: ['Silencio absoluto', 'Bosque sumergido', 'Kayak'],
    pricePerNight: 100,
    rating: 5.0,
    reviewCount: 89,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/Playa-del-lago-Traful-1024x576.jpg?updatedAt=1763579562703'],
    maxGuests: 2,
  },
  {
    id: 'domo-san-martin',
    name: 'Domo Lácar',
    cityId: 'san-martin-andes',
    city: 'San Martín de los Andes',
    type: 'domo',
    description: 'Boutique de montaña con vista al lago y gastronomía patagónica.',
    amenities: ['Vista lago Lácar', 'Gastronomía', 'Spa', 'Ski'],
    pricePerNight: 155,
    rating: 4.9,
    reviewCount: 198,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/sanmartin2.jpg?updatedAt=1763579562659'],
    maxGuests: 4,
  },
  {
    id: 'domo-lanin',
    name: 'Domo Volcán',
    cityId: 'volcan-lanin',
    city: 'Junín de los Andes',
    type: 'domo',
    description: 'Aventura y astroturismo con vista al imponente Volcán Lanín.',
    amenities: ['Vista volcán', 'Trekking', 'Cultura mapuche', 'Pesca'],
    pricePerNight: 120,
    rating: 4.8,
    reviewCount: 145,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/sanmartin.jpg?updatedAt=1763579562845'],
    maxGuests: 3,
  },
  {
    id: 'domo-mendoza',
    name: 'Domo Malbec',
    cityId: 'mendoza',
    city: 'Mendoza',
    type: 'domo',
    description: 'En viñedos con spa y vista espectacular a la cordillera.',
    amenities: ['En viñedo', 'Spa', 'Catas', 'Vista cordillera'],
    pricePerNight: 200,
    rating: 4.9,
    reviewCount: 412,
    images: [
      'https://ik.imagekit.io/ankxi835d/rutasimg/vacaciones-invierno-que-hacer-mendoza-vinedos-y-montana.webp?updatedAt=1763067641238',
    ],
    maxGuests: 4,
  },
  {
    id: 'domo-potrerillos',
    name: 'Domo Embalse',
    cityId: 'potrerillos',
    city: 'Potrerillos',
    type: 'domo',
    description: 'Lacustre con orientación al embalse y deportes acuáticos.',
    amenities: ['Vista embalse', 'Kayak', 'Rafting', 'Trekking'],
    pricePerNight: 110,
    rating: 4.8,
    reviewCount: 156,
    images: [
      'https://ik.imagekit.io/ankxi835d/rutasimg/potrerillos-y-como-ir-al-dique-de-mendoza_18294_202505121950310.jpg?updatedAt=1765077510424',
    ],
    maxGuests: 4,
  },
  {
    id: 'domo-barreal',
    name: 'Domo Astronómico',
    cityId: 'calingasta',
    city: 'Calingasta',
    type: 'domo',
    description: 'Desértico y astronómico con cielos más limpios del país.',
    amenities: ['Telescopio', 'Observatorio', 'Cabalgatas', 'Vino altura'],
    pricePerNight: 130,
    rating: 5.0,
    reviewCount: 98,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/caliangasta.jpg?updatedAt=1765077509609'],
    maxGuests: 2,
  },
  {
    id: 'domo-san-juan',
    name: 'Domo Syrah',
    cityId: 'san-juan',
    city: 'San Juan',
    type: 'domo',
    description: 'Desértico moderno integrado al paisaje árido con enoturismo.',
    amenities: ['Moderno', 'Bodegas', 'Olivos', 'Piscina'],
    pricePerNight: 95,
    rating: 4.7,
    reviewCount: 78,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/sanmjuan.jpg?updatedAt=1765077510578'],
    maxGuests: 3,
  },
  {
    id: 'domo-huaco',
    name: 'Domo Colonial',
    cityId: 'huaco',
    city: 'Huaco',
    type: 'domo',
    description: 'Rústico cultural integrado al entorno histórico de la quebrada.',
    amenities: ['Histórico', 'Senderismo', 'Fotografía'],
    pricePerNight: 55,
    rating: 4.6,
    reviewCount: 34,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/huaco.jpg?updatedAt=1765077510561'],
    maxGuests: 2,
  },
  {
    id: 'domo-talampaya',
    name: 'Domo Cañón',
    cityId: 'villa-union',
    city: 'Villa Unión',
    type: 'domo',
    description: 'Estilo desértico con orientación a formaciones rocosas de Talampaya.',
    amenities: ['Tours Talampaya', 'Astroturismo', 'Geoturismo'],
    pricePerNight: 100,
    rating: 4.8,
    reviewCount: 123,
    images: ['https://ik.imagekit.io/ankxi835d/rutasimg/villaunion.jpg?updatedAt=1765077509398'],
    maxGuests: 3,
  },
  {
    id: 'domo-rioja',
    name: 'Domo Torrontés',
    cityId: 'la-rioja',
    city: 'La Rioja',
    type: 'domo',
    description: 'Urbano ecológico con integración a circuitos del vino y termas.',
    amenities: ['Céntrico', 'Bodegas', 'Termas', 'WiFi'],
    pricePerNight: 80,
    rating: 4.7,
    reviewCount: 89,
    images: ['/placeholder.svg?height=400&width=600'],
    maxGuests: 3,
  },
];

